package com.stephen.crawler.entity;

public class Info {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column info.NAME
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column info.VALUE
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column info.NAME
	 * @return  the value of info.NAME
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column info.NAME
	 * @param name  the value for info.NAME
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column info.VALUE
	 * @return  the value of info.VALUE
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column info.VALUE
	 * @param value  the value for info.VALUE
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	public void setValue(String value) {
		this.value = value;
	}
}