package com.stephen.crawler.entity;

import com.stephen.crawler.entity.Info;

public interface InfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table info
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	int insert(Info record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table info
	 * @mbggenerated  Sun Apr 02 19:27:04 CST 2017
	 */
	int insertSelective(Info record);
}